### ISSUE TITLE
[SUGGESTION]: Change external links

### ISSUE THREAD

**Issue by Jaaslet** [Crobat4/pokeclicker#58]
### Current Behavior

All the links in externalLinksModal.html in this branch points to the main pokeclicker branch.

### Improved Behavior

Change the links in externalLinksModal.html to point to your stuff.

### Reason for change

Would create less confusing. We sometimes get bug reports/suggestions on our discord/github that we don't understand, because they are playing on your branch.

### Detailed Description

I can see that you have made your own wiki branch. The wiki link could point there. The github link could point to here, and maybe the subreddit and discord link could be replaced with a link to a 4chan thread? (not sure how 4chan works...).

Thanks!

**Comment by Crobat4** [comment]
Done 👍
